spring:
  profiles: development
druidpool:
  monitor:
    user: root
    pass: root
    allow:
    deny:
    mapping: "/druid/*"
    exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  lock:
    sync-prefix: lock_sync_gpbOlR9f_
    timeout: 5
  name:
    - days
  driver-class-name: com.mysql.jdbc.Driver
  dbtype: mariadb
  url:
    - jdbc:mysql://139.224.8.150:3306/days?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
  username:
    - root
  password:
    - Mpc7wElaDT5qBoUNxb9l+vSORWWTbKn4kPYv9Hqbyee4+MSVEJFykF6uDTd9aKVM4njsiyB5/hmdCHRRenVvNQ==
  merge-sql: true
  log-slow-sql: true
  global-datasource-stat: false
  slow-sql-millis:
    - 3000
  filters: stat,wall,log4j,config
  max-active:
    - 20
  initial-size:
    - 1
  max-wait:
    - 60000
  min-idle:
    - 1
  time-between-eviction-runs-millis:
    - 60000
  min-evictable-idle-time-millis:
    - 300000
  validation-query: select 'UPGCREDIT'
  test-while-idle: true
  test-on-borrow: false
  test-on-return: false
  pool-prepared-statements: true
  max-open-prepared-statements:
    - 20
  connection-properties:
    - config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAINGU2tylzoqPGiG+UvaeuiVutShTv/XzbMxhw9bSeGs/M2VMNZ89Xd3VpIyGpeUjP7flF6lrXrAjmO5y2sQUcECAwEAAQ==
server:
  port: 10101
  display-name: upgcredit-channelapi-dev-01
  error:
    whitelabel:
      enabled: false
mybatis:
  type-aliases-package: com.wpmac.mzehtapi.po
  check-config-location: true
api:
  common: "http://10.10.168.79:10100/"
  corp: "http://10.10.168.28:10102"
logback:
  level: "DEBUG"
---
spring:
  profiles: production
druidpool:
   monitor:
    user: root
    pass: upg-credit-monitor
    allow:
    deny:
    mapping: "/druid/*"
    exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
   lock:
    sync-prefix: lock_sync_gpbOlR9f_
    timeout: 5
   name:
    - days
   driver-class-name: com.mysql.jdbc.Driver
   dbtype: mariadb
   url:
    - jdbc:mysql://139.224.8.150:3306/days?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
   username:
    - mysql
   password:
    - Mpc7wElaDT5qBoUNxb9l+vSORWWTbKn4kPYv9Hqbyee4+MSVEJFykF6uDTd9aKVM4njsiyB5/hmdCHRRenVvNQ==
   merge-sql: true
   log-slow-sql: true
   global-datasource-stat: false
   slow-sql-millis:
    - 3000
   filters: stat,wall,log4j,config
   max-active:
    - 20
   initial-size:
    - 1
   max-wait:
    - 60000
   min-idle:
    - 1
   time-between-eviction-runs-millis:
    - 60000
   min-evictable-idle-time-millis:
    - 300000
   validation-query: select 'UPGCREDIT'
   test-while-idle: true
   test-on-borrow: false
   test-on-return: false
   pool-prepared-statements: true
   max-open-prepared-statements:
    - 20
   connection-properties:
    - config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAINGU2tylzoqPGiG+UvaeuiVutShTv/XzbMxhw9bSeGs/M2VMNZ89Xd3VpIyGpeUjP7flF6lrXrAjmO5y2sQUcECAwEAAQ==
server:
  port: 10101
  display-name: upgcredit-channelapi-pro-01
  error:
      whitelabel:
        enabled: false
mybatis:
  type-aliases-package: com.wpmac.mzehtapi.po
  check-config-location: true
api:
  common: "http://10.10.168.79:10100/"
  corp: "http://10.10.168.28:10102"